[package]
name = "horned-owl"
version = "0.3.0"
authors = ["Phillip Lord <phillip.lord@russet.org.uk>"]

[dependencies]
quick-xml="0.12.4"
curie = "0.0.8"
clap = "2.31.2"

[dev-dependencies]
bencher = "0.1.4"
mktemp = "0.3.1"

[[bench]]
name = "horned"
harness = false